### ISSUE TITLE
Evaluation Metrics 

### ISSUE THREAD

**Issue by seyeeet** [EricGuo5513/action-to-motion#1]
Hello
Thanks for share your code and thanks for your great paper.

In the paper, in the evaluation metrics part, 4 metrics are being used for evaluations, namely: FID, Recognition Score, Diversity, and Multimodality.
I could not see the evaluation metrics in the implementation repo, and this causes me to not be able to reproduce the results in the paper.
Could you kindly please add the evaluation metrics to your repo?

Thanks in advance!

Sey

**Comment by EricGuo5513** [comment]
Hi Sey,

Thanks for your interest on our work. I didn't put the evaluation part on
repo because this part of code is kind of messy, not well-organized. I will
send you the core code these two days. That should be enough. Please remind
me if you don't recieve it util Sep 6. You could also follow the metric
computing details in our paper, which is exactly what we're doing in
implementation.

best,

Chuan

Sey Eeet <notifications@github.com> 于2020年9月3日周四 下午2:27写道：

**Comment by algvr** [comment]
Hi Eric, amazing work!

Could you please send me the code to train the evaluation classifier (MotionDiscriminator/MotionDiscriminatorForFID; the one used in eval_scripts/load_classifier.py)? No need to clean the code, I just want to reproduce your evaluation procedure correctly for another dataset. Thank you very much in advance!
